Горшенин Дмитрий гр. 6214 вариант №3 лаба 4
itsecd/isb-4 pull request #14
Opened 2023-05-24 21:29 UTC by dmgorshenin

Получен БИН код карты при помощи дополнительной информации о карте,
Написан софт на python, который подобрал бы оставшиеся цифры номера карты по ее хэшу.
Замерено время, потраченное на поиск коллизии при различном числа процессов в пуле, и результат визуализирован средствами matplotlib.
Написана собственная реализацию алгоритма Луна и выяснено, является ли полученный номер карты корректным.

2023-05-25 06:21 UTC, alxmcs requested changes

2023-05-25 06:21 UTC, alxmcs commented on files/_create_settings.py
> +    'bin': 'files/bin.txt',
Бины, хеш и 4 последние цифры вынести в json с настройками в виде значений, а не в виде пути к txt файлам

2023-05-25 06:21 UTC, alxmcs commented on files/_create_settings.py
> +    'card_number': 'files/card_number.txt',
Результаты работы софта лучше хранить в каком-нибудь формает сериализации, а не плейн текстом

2023-05-25 06:21 UTC, alxmcs commented on system_files/card_recovery.py
> +                      for i in range(100000, 1000000)]
Не учтено, что подбираемая комбинация цифр может начинатсья с нуля

2023-05-25 06:21 UTC, alxmcs commented on system_files/card_recovery.py
> +from tqdm import tqdm
Использовать tqdm совместно с графическим интерфейсом - такая себе идея. Ты либо взаимодейсвуешь с пользователем через консоль, либо через гуи, но не одновременно

2023-05-25 13:56 UTC, alxmcs requested changes

2023-05-25 13:56 UTC, alxmcs commented on main_window.py
> +from system_files.card_recovery import *
За `import *` [на районе убивают](https://stackoverflow.com/questions/2386714/why-is-import-bad)

2023-05-25 13:56 UTC, alxmcs commented on main_window.py
> +class RecoveryCardGUI(QMainWindow):
RecoveryCardGUI должен заниматься GUI и не должен заниматься отрисовкой графиков.

Сейчас этот класс нарушает SRP

2023-05-25 13:56 UTC, alxmcs commented on system_files/card_recovery.py
> +class RecoverySystem:
Тут аналогичная ситуация - в одном классе осуществляется подбор номера, алгоритм Луна и работа с файлами

2023-05-28 14:43 UTC, alxmcs approved these changes

2023-05-28 14:46 UTC, dmgorshenin commented
а вы закроете лабу?

2023-05-28 14:48 UTC, closed without merging