6211-100503D Кадников Егор Вадимович Лаб.4 Вар.7
itsecd/isb-4 pull request #17
Opened 2023-05-26 14:00 UTC by acebiscuits

От меня требовалось:
Выяснить БИН код карты при помощи дополнительной информации о карте,
Написать софт на python, который подобрал бы оставшиеся цифры номера карты по ее хэшу.
Замерить время, потраченное на поиск коллизии при различном числа процессов в пуле, и визуализировать его средствами matplotlib.
Написать собственную реализацию алгоритма Луна и выяснить, является ли полученный номер карты корректным.

2023-05-28 14:47 UTC, alxmcs requested changes

2023-05-28 14:47 UTC, alxmcs commented on useful_funcs.py
> +                    data["card_number"] = f"{result}"
Здесь дейсвительно нужен f-стринг?

2023-05-28 14:47 UTC, alxmcs commented on useful_funcs.py
> +    print(data)
Заменить на логирование

2023-05-28 14:47 UTC, alxmcs commented on useful_funcs.py
> +        print(res)
Заменить на логирование

2023-05-28 14:47 UTC, alxmcs commented on useful_funcs.py
> +            print(b)
Заменить на логирование

2023-05-28 14:47 UTC, alxmcs commented on useful_funcs.py
> +                    print(f'we have found {result} and have terminated pool')
Заменить на логирование

2023-05-29 17:45 UTC, acebiscuits commented on useful_funcs.py
> +                    print(f'we have found {result} and have terminated pool')
все на логгирование заменил

2023-05-29 17:46 UTC, acebiscuits commented on useful_funcs.py
> +                    data["card_number"] = f"{result}"
убрал f-стринг

2023-05-30 06:27 UTC, alxmcs approved these changes

2023-05-30 06:28 UTC, closed without merging