6212-100503D Куспанова Дания, Лаба №4, Вариант 8
itsecd/isb-4 pull request #18
Opened 2023-05-26 15:45 UTC by d7anSeR

1. Выяснить БИН код карты при помощи дополнительной информации о карте,
2. Написать софт на python(хотя, потенциально, можно и на любом другом языке), который подобрал бы оставшиеся цифры номера карты по ее хешу, с использованием библиотеки multiprocessing.
3. Замерить время, потраченное на поиск коллизии при различном числа процессов в пуле, и визуализировать его средствами matplotlib (или другой аналогичной библиотеки),
4. Написать собственную реализацию алгоритма Луна и выяснить, является ли полученный номер карты корректным.

2023-05-28 15:26 UTC, alxmcs requested changes

2023-05-28 15:26 UTC, alxmcs commented on app.py
> +        write_file(self.dict_path["path_default_hash"],
Зачем в результате работы софта записывать в файлы исходные данные (которые должны быть доступны изначально) , для меня загадка

2023-05-28 15:26 UTC, alxmcs commented on work_with_file.py
> +    logging.basicConfig(level=logging.INFO, filename="py_log.log")
Настройки логирования можно вынести на уровень модуля, чтобы не повторять одну и ту же строку кода в каждой функции

2023-05-28 15:26 UTC, alxmcs commented on app.py
> +        layout.addWidget(
Не надо выводить захардкоженные данные. Хотя бы бери их из настроек

2023-05-28 15:26 UTC, alxmcs commented on app.py
> +    def initUI(self) -> None:
Этот метод - для инициализации элементов gui, прочие атрибуты лучше убрать под `__init__`

2023-05-28 15:26 UTC, alxmcs commented on check_card.py
> +from tqdm import tqdm
У тебя приложение имеет графический интерфейс. Хочешь демонстрировать прогресс- демонстрируй pyqtшным прогресс баром (ну или вообще не демонстрируй, осуждать не буду). Выводить прогресс бар в консоль - не сильно полезно.

2023-05-28 17:38 UTC, d7anSeR commented
исправила ошибки и удалила ненужные txt-шные файлы

2023-05-29 14:31 UTC, alxmcs approved these changes

2023-05-29 15:19 UTC, closed without merging