6212 Пахомов Л. А. Лаб 4 Вар.13
itsecd/isb-4 pull request #20
Opened 2023-05-27 19:05 UTC by Sonya-From-IBAS

В этой лабораторной работе было необходимо восстановить номер карты, зная ее бин, последние 4 цифры, а так же ее хэш, алгоритм - blake2s. Так же с помощью библиотеки multiprocessing нужно было вычислить время работы подбора номера с разным количеством ядер(1-8 в моем случае). В конце нужно было проверить номер карты с помощью алгоритма Луна, результатом выполнения которого номер был признан некорректным. Функция подбора номера находится в файле card_number.py, алгоритм Луна в luhn_algorithm.py, а так же два класса - для работы с графиком и работы с файлами

2023-05-28 15:31 UTC, alxmcs requested changes

2023-05-28 15:31 UTC, alxmcs commented on .vscode/settings.json
> +{
Служебные файлы IDE из репозитория убрать

2023-05-28 15:31 UTC, alxmcs commented on files/settings.json
> +    "hash":"./files/hash.txt",
Заменить на значения. Зачем тебе отдельный файл, в котором лежит единственная строка?

2023-05-28 15:31 UTC, alxmcs commented on files/settings.json
> +    "bins":"./files/bins.txt",
Аналогично

2023-05-28 15:31 UTC, alxmcs commented on files/settings.json
> +    "lastNumbers":"./files/lastNumbers.txt",
Аналогично

2023-05-28 15:31 UTC, alxmcs commented on scripts/menu.py
> +    if args.cardnumber is not None:
Синтаксически избыточное условие

2023-05-28 15:31 UTC, alxmcs commented on scripts/menu.py
> +    elif args.corestime is not None:
Синтаксически избыточное условие

2023-05-28 17:50 UTC, Sonya-From-IBAS commented
По поводу вынесения информации из txt файлов в json. У меня в bin.txt лежит 10 строчек разных бинарников, хранить их в json не очень комфортно. Но если я положу значения последних цифр и хэша в json, то мне придется не только переписать функции, но и добавить еще(вытаскивание занчений либо из json либо из txt). Тем самым я усложню код, потому что буду вызывать много похожих функций, которые, по сути, делают одно и то же. А вызов функций очень сильно нагружает программу

2023-05-28 17:50 UTC, Sonya-From-IBAS commented
Может, можно оставить так?

2023-05-29 10:15 UTC, Sonya-From-IBAS commented
Я все исправил, добавил bin, hash, last numbers и card info в settings.json. Txt файлы убрал

2023-05-29 14:32 UTC, alxmcs approved these changes

2023-06-03 16:45 UTC, closed without merging