Сысолятин Егор Максимович 6212-100503D вар 4
itsecd/isb-4 pull request #26
Opened 2023-05-29 19:25 UTC by RYTpL

2023-05-30 06:54 UTC, alxmcs requested changes

2023-05-30 06:54 UTC, alxmcs commented on executable_files/menu.py
> +                       help="Зruns the Luhn algorithm")
>Зruns

2023-05-30 06:54 UTC, alxmcs commented on executable_files/menu.py
> +        print(f"card number is {number}")
Заменить на logging

2023-05-30 17:18 UTC, RYTpL commented
конкретно так проработал logging, все остальное тоже исправил

вт, 30 мая 2023 г. в 10:54, alxmcs ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1209778808>:
>
> > +logging.getLogger().setLevel(logging.INFO)
> +
> +def menu() -> None:
> +    """
> +    Func for working with user
> +    """
> +    parser = argparse.ArgumentParser()
> +    group = parser.add_mutually_exclusive_group(required=True)
> +    parser.add_argument(
> +        "path", type=str, help="The path to the json file with the settings")
> +    group.add_argument("-cn", "--cardnumber",
> +                       help="Runs the script for finding the card number")
> +    group.add_argument("-ct", "--corestime",
> +                       help="Runs a script to measure the time")
> +    group.add_argument("-la", "--luhnalg",
> +                       help="Зruns the Luhn algorithm")
>
> Зruns
>
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1209779550>:
>
> > +    parser = argparse.ArgumentParser()
> +    group = parser.add_mutually_exclusive_group(required=True)
> +    parser.add_argument(
> +        "path", type=str, help="The path to the json file with the settings")
> +    group.add_argument("-cn", "--cardnumber",
> +                       help="Runs the script for finding the card number")
> +    group.add_argument("-ct", "--corestime",
> +                       help="Runs a script to measure the time")
> +    group.add_argument("-la", "--luhnalg",
> +                       help="Зruns the Luhn algorithm")
> +    args = parser.parse_args()
> +    if args.cardnumber:
> +        card_info = CardInfo(args.path)
> +        number = create_card_number(
> +            card_info.hash_card, card_info.last_num, card_info.bins_card, 8)
> +        print(f"card number is {number}")
>
> Заменить на logging
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1209779607>:
>
> > +        print(f"card number is {number}")
> +        card_info.card_number_serealization(number, args.path)
> +    elif args.corestime:
> +        card_info = CardInfo(args.path)
> +        stat = Stat(args.path)
> +        for i in range(1, 9):
> +            start = time.perf_counter()
> +            create_card_number(card_info.hash_card,
> +                               card_info.last_num, card_info.bins_card, i)
> +            end = time.perf_counter()
> +            stat.time_serialization(i, end-start)
> +        stat.save_fig()
> +    elif args.luhnalg:
> +        card_info = CardInfo(args.path)
> +        number = card_info.card_number_deserealization(args.path)
> +        print(luhn_algorithm(number))
>
> Заменить на logging
> ------------------------------
>
> In executable_files/card_number.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1209781467>:
>
> > @@ -0,0 +1,34 @@
> +import hashlib
> +import multiprocessing as mp
> +import typing
> +import logging
> +
> +from tqdm import tqdm
> +
> +logging.getLogger().setLevel(logging.INFO)
> +
> +def compare_hash_with_number(number:str, hash:str, bin:str, last_numbers:str)->typing.Optional[str]:
> +    """
> +    Func that converts a number to a hash and compares it with a given hash
> +    """
> +    curNumber = "".join([bin,number,last_numbers])
>
> f"{bin}{number}{last_numbers}"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/itsecd/isb-4/pull/26#pullrequestreview-1450183909>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3FJNHFC2TPX646DSVHZITTXIWKSBANCNFSM6AAAAAAYTDGWXY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-05-31 09:25 UTC, alxmcs requested changes

2023-05-31 09:25 UTC, alxmcs commented on executable_files/card_number.py
> +                    logging.info("Card number is founded")
![image](https://github.com/itsecd/isb-4/assets/70561974/83943624-2cc3-460e-9608-19a2d970c9cf)

2023-05-31 09:25 UTC, alxmcs commented on executable_files/menu.py
> +    # Create an argument parser
Комменты вне докстрингов убрать

2023-05-31 09:25 UTC, alxmcs commented on executable_files/menu.py
> +    # Define some functions for the script logic
Комменты вне докстрингов убрать

2023-05-31 09:25 UTC, alxmcs commented on executable_files/menu.py
> +    # Execute the script logic based on the arguments
Комменты вне докстрингов убрать

2023-05-31 09:25 UTC, alxmcs commented on executable_files/menu.py
> +            print(luhn_algorithm(number))
Либо через logging, либо убрать

2023-05-31 09:25 UTC, alxmcs commented on executable_files/menu.py
> +            print(f"card number is {number}")
Либо через logging, либо убрать

2023-06-02 08:44 UTC, RYTpL commented
выполнено

ср, 31 мая 2023 г. в 13:26, alxmcs ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In executable_files/card_number.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211358718>:
>
> > +    return None
> +
> +def create_card_number(hash:str, last_numbers:str, bins:tuple, cores:int)->typing.Optional[str]:
> +    """
> +    Func that generate uniq numbers for card number
> +    """
> +    values = []
> +    n = 1
> +    for bin in bins:
> +        for i in range(1000000):
> +            values.append((str(i).zfill(6), hash, str(bin), last_numbers))
> +        with mp.Pool(processes=cores) as p:
> +            for i in p.starmap(compare_hash_with_number, tqdm(values, desc="processing ...", ncols=100)):
> +                if i is not None:
> +                    p.terminate()
> +                    logging.info("Card number is founded")
>
> [image: image]
> <https://user-images.githubusercontent.com/70561974/242225834-83943624-2cc3-460e-9608-19a2d970c9cf.png>
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211359309>:
>
> > +import logging
> +
> +from executable_files.card_info import CardInfo
> +from executable_files.luhn_algorithm import luhn_algorithm
> +from executable_files.card_number import create_card_number
> +from executable_files.cores_time import Stat
> +
> +logging.getLogger().setLevel(logging.INFO)
> +
> +def menu() -> None:
> +    """
> +    Func for working with user
> +    """
> +    logger = logging.getLogger(__name__)
> +
> +    # Configure the logging level and format
>
> Комменты вне докстрингов убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211359404>:
>
> > +from executable_files.luhn_algorithm import luhn_algorithm
> +from executable_files.card_number import create_card_number
> +from executable_files.cores_time import Stat
> +
> +logging.getLogger().setLevel(logging.INFO)
> +
> +def menu() -> None:
> +    """
> +    Func for working with user
> +    """
> +    logger = logging.getLogger(__name__)
> +
> +    # Configure the logging level and format
> +    logging.basicConfig(level=logging.DEBUG, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
> +
> +    # Create a file handler to write error messages to a file
>
> Комменты вне докстрингов убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211359525>:
>
> > +
> +def menu() -> None:
> +    """
> +    Func for working with user
> +    """
> +    logger = logging.getLogger(__name__)
> +
> +    # Configure the logging level and format
> +    logging.basicConfig(level=logging.DEBUG, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
> +
> +    # Create a file handler to write error messages to a file
> +    file_handler = logging.FileHandler("log.txt")
> +    file_handler.setLevel(logging.ERROR)
> +    logger.addHandler(file_handler)
> +
> +    # Create an argument parser
>
> Комменты вне докстрингов убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211359633>:
>
> > +    logger.addHandler(file_handler)
> +
> +    # Create an argument parser
> +    parser = argparse.ArgumentParser()
> +    group = parser.add_mutually_exclusive_group(required=True)
> +    parser.add_argument(
> +        "path", type=str, help="The path to the json file with the settings")
> +    group.add_argument("-cn", "--cardnumber",
> +                    help="Runs the script for finding the card number")
> +    group.add_argument("-ct", "--corestime",
> +                    help="Runs a script to measure the time")
> +    group.add_argument("-la", "--luhnalg",
> +                    help="Runs the Luhn algorithm")
> +    args = parser.parse_args()
> +
> +    # Log the arguments
>
> Комменты вне докстрингов убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211359718>:
>
> > +    parser = argparse.ArgumentParser()
> +    group = parser.add_mutually_exclusive_group(required=True)
> +    parser.add_argument(
> +        "path", type=str, help="The path to the json file with the settings")
> +    group.add_argument("-cn", "--cardnumber",
> +                    help="Runs the script for finding the card number")
> +    group.add_argument("-ct", "--corestime",
> +                    help="Runs a script to measure the time")
> +    group.add_argument("-la", "--luhnalg",
> +                    help="Runs the Luhn algorithm")
> +    args = parser.parse_args()
> +
> +    # Log the arguments
> +    logger.debug(f"Arguments: {args}")
> +
> +    # Define some functions for the script logic
>
> Комменты вне докстрингов убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211359819>:
>
> > +        This function takes one argument: number
> +        It applies the Luhn algorithm to the card number to check its validity
> +        It returns True if the number is valid and False otherwise
> +        """
> +        logger.debug(f"Applying Luhn algorithm to {number}")
> +        return result
> +
> +    def save_fig():
> +        """
> +        This function does not take any arguments
> +        It saves a figure of the time measurements to a file
> +        It does not return anything
> +        """
> +        logger.debug(f"Saving figure")
> +
> +    # Execute the script logic based on the arguments
>
> Комменты вне докстрингов убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211360505>:
>
> > +            stat = Stat(args.path)
> +            for i in range(1, 9):
> +                start = time.perf_counter()
> +                create_card_number(card_info.hash_card,
> +                                card_info.last_num, card_info.bins_card, i)
> +                end = time.perf_counter()
> +                stat.time_serialization(i, end-start)
> +            stat.save_fig()
> +            logger.info(f"Time measurement and figure saving completed successfully")
> +        except Exception as e:
> +            logger.error(f"An error occurred while measuring time or saving figure: {e}")
> +    elif args.luhnalg:
> +        try:
> +            card_info = CardInfo(args.path)
> +            number = card_number_deserealization(args.path)
> +            print(luhn_algorithm(number))
>
> Либо через logging, либо убрать
> ------------------------------
>
> In executable_files/menu.py
> <https://github.com/itsecd/isb-4/pull/26#discussion_r1211360776>:
>
> > +
> +    def save_fig():
> +        """
> +        This function does not take any arguments
> +        It saves a figure of the time measurements to a file
> +        It does not return anything
> +        """
> +        logger.debug(f"Saving figure")
> +
> +    # Execute the script logic based on the arguments
> +    if args.cardnumber:
> +        try:
> +            card_info = CardInfo(args.path)
> +            number = create_card_number(
> +                card_info.hash_card, card_info.last_num, card_info.bins_card, 8)
> +            print(f"card number is {number}")
>
> Либо через logging, либо убрать
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/itsecd/isb-4/pull/26#pullrequestreview-1452616994>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3FJNHBBU7QBC2YV6JE2MJLXI4FDFANCNFSM6AAAAAAYTDGWXY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-06-03 13:20 UTC, alxmcs approved these changes

2023-06-03 13:20 UTC, alxmcs commented
Зачтено

2023-06-03 13:20 UTC, closed without merging