6211 Богачев Матвей Иванович
itsecd/isb-4 pull request #27
Opened 2023-05-30 19:44 UTC by Matosik

В данной лабораторной работе я очень подробно познакомился с библиотекой hashlib и преисполнился в познании хэша и данной области и мне хватило 40 строчек кода, чтобы найти карту по ее хэшу. Я конечно не претендую на зачтение данной лабораторной работы с таким кодом, но до меня еще никто так не делал можно за креативность зачесть данную лабораторную работу?  молю....

2023-05-30 19:45 UTC, Matosik commented
![image](https://github.com/itsecd/isb-4/assets/113327388/7d64377b-2feb-42ea-acd1-3c05416434fb)

2023-05-30 19:50 UTC, Matosik commented
![image](https://github.com/itsecd/isb-4/assets/113327388/15e3cc8c-1da5-4e0d-9b7d-3f3a22916178)

2023-05-31 08:55 UTC, Gironape commented
Это гений какой-то... извините

2023-05-31 09:30 UTC, alxmcs requested changes
* нет реализации алгоритма Луна и проверки полученного номера карты
* нет построения графика времени брутфорса от числа выделенных процессов
* зато есть картинки на религиозные темы в пул риквесте

2023-05-31 09:30 UTC, alxmcs commented on main.py
> +    hash = "140495200b351b7f18a46e3796f2875ebdf0023568933ef3b99efb285af3f06b"
Вынести в натсройки приложения

2023-05-31 09:30 UTC, alxmcs commented on main.py
> +    print("good card = ", good_card)  # 547905 415657 2301
Заменить на logging или убрать

2023-06-03 12:32 UTC, Matosik commented
В данной лабораторной работе было реализовано:
-Поиск карты по ее хэшу с известным бином и последними 4 цифрами
-Хэш считался с помощью несколько процессоров(multiprocessing) благодаря чему процесс поиска хэша выполнялся в разы быстрее. Это мы можем заметить на графике, который строился с помощью библиотеки matplotlib
-Так же для взаимодействия с пользователем был сделан простенький графический интерфейс с помощью библии PyQt5
-Реализован алгоритм луна, который позволяет узнать является ли номер карты корректным

2023-06-03 13:28 UTC, alxmcs requested changes

2023-06-03 13:28 UTC, alxmcs commented on CONFIG.py
> +CONFIG = {
Под настройками подразумевается отдельный файл в общепринятом формате сериализации, а не скрипт с единственной константой внутри

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +def compute_hash(data:int):
compute_hash встречается в исходниках два раза

2023-06-03 13:28 UTC, alxmcs commented on other.py
> +def compute_hash(card: int) -> int:
compute_hash встречается в исходниках два раза

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +def luna(card: int):
luna встречается в исходниках два раза

2023-06-03 13:28 UTC, alxmcs commented on other.py
> +def luna(card: int) -> bool:
luna встречается в исходниках два раза

2023-06-03 13:28 UTC, alxmcs commented on charting.py
> +    cores, times = zip(*results)  # разделяем данные на два списка
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +    #one step
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +    #two step
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +    #three step
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +        logging.info(f"Найденая карта: {good_card}")  # 547905 415657 2301
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on other.py
> +    # one step
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on other.py
> +    # three step
Комменты вне докстрингов убрать

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +def luna(card: int):
Нет докстринга

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +    bin = [527576, 543763, 547964, 515460, 527404, 531310, 533669, 536961, 538150, 545152, 546901,
Параметр все еще не вынесен в настройки приложения

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +    number_last = 2301
Параметр все еще не вынесен в настройки приложения

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +    hash = "140495200b351b7f18a46e3796f2875ebdf0023568933ef3b99efb285af3f06b"
Параметр все еще не вынесен в настройки приложения

2023-06-03 13:28 UTC, alxmcs commented on main.py
> +            print(card)
Все еще нет логирования

2023-06-03 13:28 UTC, alxmcs commented on main_window.py
> +        # 5479 0541 5657 2301
Комменты вне докстринга убрать

2023-06-03 14:44 UTC, Matosik commented
исправил 
![image](https://github.com/itsecd/isb-4/assets/113327388/6fcbc8a2-1955-4279-a51c-079a5337f699)

2023-06-05 08:09 UTC, alxmcs approved these changes
Думаю, в таком виде код можно принять

2023-06-05 08:11 UTC, closed without merging

2023-06-05 11:51 UTC, Matosik commented
![image](https://github.com/itsecd/isb-4/assets/113327388/7e001efd-4adc-443d-a9cc-495daf555a34)