6211-100503D Замотохина Мария Лаб.4 Вар.5
itsecd/isb-4 pull request #30
Opened 2023-05-31 20:01 UTC by ZamotohinaMaria

все реализовано в виде приложения, но не работает прогресс бар и вывод информации на экран при поиске карты и создании графика, отладка решения проблемы не дала(

2023-06-02 05:40 UTC, alxmcs requested changes
я бы рекомендовал в качестве комметариев к коммитам указывать, какие задачи решены или какой функционал добавлен, а не персональные переживания
![image](https://github.com/itsecd/isb-4/assets/70561974/d8cf8636-88e3-4bf6-935c-07f95cad40ac)

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +data = {
Вынести константы в настройки, чтобы для подбора другого номера карты не приходилось редактировать исходники

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +BIN = ['510126', '519778', '521178','522828','523701',
Аналогично

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +def check_hash(x: int)-> tuple:
Нет докстринга

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +def find_card_num() -> str:
Нет докстринга

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +def time_research(c: int) -> float:
Нет докстринга

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +def create_bar(times: np.ndarray) -> None:
Нет докстринга

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +def algorithm_luna(number: str) -> bool:
Нет докстринга

2023-06-02 05:40 UTC, alxmcs commented on window.py
> +        # im = QPixmap('researches.png')
Закомментированный код убрать

2023-06-02 05:40 UTC, alxmcs commented on window.py
> +        #self.pbar.show()
Закомментированный код убрать

2023-06-02 05:40 UTC, alxmcs commented on oib-laba-4.py
> +    #logging.basicConfig(level=logging.INFO, filename='logs.log', filemode='w')
Закомментированный код убрать

2023-06-02 05:40 UTC, alxmcs commented on oib-laba-4.py
> +# |5|4006234246b4fd2b2833d740927ab20465afad862c74b1a88ec0869bde5c836c|Mastercard|Дебетовая|Альфа-банк|0254|sha256|
Комментарии вне докстрингов убрать

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +                #logging.info(f'Number of card: {result}, cores = {c}')
Закомментированный код убрать

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +                print(f'Number of card: {result[0]}-{result[1]}-{data["last_num"]}')
Либо `logging`, либо удалить

2023-06-02 05:40 UTC, alxmcs commented on functions.py
> +                print(f'Number of card: {result[0]}{result[1]}{data["last_num"]}, cores = {c}')
Либо `logging`, либо удалить

2023-06-02 19:40 UTC, ZamotohinaMaria commented
Все правки внесла, только не поняла, что значит вынести в настройки BIN и data

2023-06-03 13:34 UTC, alxmcs requested changes

2023-06-03 13:34 UTC, alxmcs commented on functions.py
> +data = {
Эти данные  необходимо вынести в отдельный файл в общепринятом формате сериализации, а при работе софта указывать к ним путь и десериализовывать.

Надеюсь, я достаточно подробно объяснил, что подразумевалось под вынесением в настройки.

Потому что сейчас для того, чтобы подбрать по хешу какую-нибудь другую карту, требуется изменить исходники твоего софта. Хотелось бы, чтобы софт был генерализован.

2023-06-03 13:34 UTC, alxmcs commented on functions.py
> +BIN = ['510126', '519778', '521178', '522828', '523701',
Аналогично эти данные.
Кто-то из твоих однокурсников достаточно успешно сериализовывал/десериализовывал эти настройки в json, посмотри в закрытых пул-риквестах.

2023-06-05 17:05 UTC, ZamotohinaMaria commented
Данные о хеше, бинах и тд вынесены в файлы, подправлен интерфейс, прогресс бар заработал

2023-06-06 14:06 UTC, alxmcs commented on functions.py
> +# data = {
Закомменченный код убрать

2023-06-06 14:06 UTC, alxmcs commented on functions.py
> +# BIN = ['510126', '519778', '521178', '522828', '523701',
Закомменченный код убрать

2023-06-06 14:08 UTC, alxmcs commented on files/settings.json
> +{"hash_file": "files/hash.txt", "bins_file": "files/bins.txt", "last_numbers_file": "files/last_numbers.txt"}
Положить значения хеша, бинов и последних цифр карты в жсон. Какой смысл хранить тут ссылки на текстовые файлы, если ты можешь десериализовать настройки прямо из жсона?

2023-06-07 07:06 UTC, alxmcs approved these changes

2023-06-07 10:17 UTC, alxmcs commented
Зачтено

2023-06-07 10:17 UTC, closed without merging