Никита Уваров 6214-100503D Лаб 4 14 вариант
itsecd/isb-4 pull request #33
Opened 2023-06-02 17:33 UTC by Rifinn-crypto

В данной лабораторной работе необходимо было восстановить номер банковской карты по ее хэшу с использованием дополнительной информации о типе карты, типе платежной системы и ее банке. Выяснить, является ли полученный номер карты корректным.

2023-06-05 08:17 UTC, alxmcs requested changes

2023-06-05 08:17 UTC, alxmcs commented on file/card_number.txt
> +5294609402360758
В качестве выходного файла сделать жсон с двумя полями - номером карты и результат проверки алгоритмом Луна

2023-06-05 08:17 UTC, alxmcs commented on main.py
> +                logging.info("Номер карты не был найден")
Это не уровень info

2023-06-05 08:17 UTC, alxmcs commented on main.py
> +                logging.info(f"Номер карты {card_number} не корректен")
Это не уровень info

2023-06-05 08:17 UTC, alxmcs commented on ploting.py
> +    plt.savefig(os.path.join(visual_directory, "statistics.png"))
Захардкоженное имя файла

2023-06-05 18:06 UTC, Rifinn-crypto commented
![1648375252_1-kartinkof-club-p-delo-sdelano-mem-1](https://github.com/itsecd/isb-4/assets/114596909/c63692ee-e296-4995-81d7-2b94c5e58d57)

2023-06-06 14:09 UTC, alxmcs approved these changes

2023-06-07 10:19 UTC, alxmcs commented
Зачтено

2023-06-07 10:19 UTC, closed without merging