Основы информационной безопасности. Лабораторная №4, 4 вариант, Карпачева Полина 6212-100503D
itsecd/isb-4 pull request #38
Opened 2023-06-03 21:33 UTC by PolinaKrp

Задание:
Выяснить БИН код карты при помощи дополнительной информации о карте,
Написать софт на python(хотя, потенциально, можно и на любом другом языке), который подобрал бы оставшиеся цифры номера карты по ее хешу, с использованием библиотеки multiprocessing.
Замерить время, потраченное на поиск коллизии при различном числа процессов в пуле, и визуализировать его средствами matplotlib (или другой аналогичной библиотеки),
Написать собственную реализацию алгоритма Луна и выяснить, является ли полученный номер карты корректным.
4 вариант. Значение хеша: e5c92fb926ffc9976ad06b46cc7eb656158f07b6e41a1666e005c9cd

2023-06-05 08:45 UTC, alxmcs requested changes

2023-06-05 08:45 UTC, alxmcs commented on graph.py
> +    items = [(i, card) for i in range(99999, 10000000)]
В этом ренже не учитываются комбинации цифр карты, начинающиеся с нуля

При этом конечное значение в 10 раз больше, чем нужно

2023-06-05 08:45 UTC, alxmcs commented on setting.py
> +SETTING = {
Настройки приложения должны быть представлены в виде файла в общепринятом формате сериализации типа json/yaml/xml/pickle/и так далее, а не в виде отдельного скрипта с одинокой константой внутри

2023-06-05 08:45 UTC, alxmcs commented on hashing.py
> +def algorithm_luna(number: str) -> bool:
Luhn

2023-06-05 12:03 UTC, PolinaKrp commented
Исправила

2023-06-06 14:20 UTC, alxmcs requested changes

2023-06-06 14:20 UTC, alxmcs commented on hashing.py
> +SETTING = {
Еще раз:

Настройки приложения должны быть представлены в виде файла в общепринятом формате сериализации типа json/yaml/xml/pickle/и так далее, а не в виде константы.

Если пользователю понадобится изменить параметры подбора карты, ему придется менять исходный код твоего приложения. Так не должно быть.

2023-06-10 09:29 UTC, alxmcs requested changes
В репозитории не хватает файла с настройками, результатом работы софта и графика

2023-06-14 07:25 UTC, PolinaKrp commented
Не могла раньше все подгрузить, ноутбук был в ремонте.

2023-06-14 08:21 UTC, closed without merging