6211 - 100503D Казаков Андрей Дмитриевич, Лаб. №4 Вариант №9
itsecd/isb-4 pull request #39
Opened 2023-06-05 10:39 UTC by Gironape

От меня требовалось:
Выяснить БИН код карты при помощи дополнительной информации о карте,
Написать софт на python, который подобрал бы оставшиеся цифры номера карты по ее хэшу.
Замерить время, потраченное на поиск коллизии при различном числа процессов в пуле, и визуализировать его средствами matplotlib.
Написать собственную реализацию алгоритма Луна и выяснить, является ли полученный номер карты корректным.

2023-06-05 10:48 UTC, alxmcs requested changes
* убрать служебные файлы IDE
* вернуть .gitignore

2023-06-05 10:48 UTC, alxmcs commented on main.py
> +    parser.add_argument('-i', '--init_path', default='file\\init_file.json', help='Путь к json файлу с данными, '
Два раза `default`

2023-06-06 14:24 UTC, alxmcs requested changes
Файлы ide все еще на месте

2023-06-06 14:24 UTC, alxmcs commented on gitignore.txt
<img src="https://github.com/itsecd/isb-4/assets/70561974/91ae7810-7232-4c33-ade1-6c917a89e2a1" width=200/>

2023-06-06 17:03 UTC, Gironape commented on gitignore.txt
![395425](https://github.com/itsecd/isb-4/assets/115278933/bb905e29-812f-4c22-8c21-0af405644c38)
Вы его у меня не отнимите

2023-06-06 18:44 UTC, alxmcs requested changes

2023-06-06 18:44 UTC, alxmcs commented on gitignore.txt
Зачем переименовывать  `.gitingnore` в `gitingnore .txt` ?
Должен быть `.gitingnore`

2023-06-06 20:09 UTC, Gironape commented on gitignore.txt
я не причастен, это оно само

2023-06-07 07:06 UTC, alxmcs approved these changes

2023-06-07 10:17 UTC, alxmcs commented
Зачтено

2023-06-07 10:17 UTC, closed without merging