6213-100503D Панюшкин Андрей Михайлович Л/Р 4, Вариант 14
itsecd/isb-4 pull request #4
Opened 2023-04-25 15:46 UTC by Santas7

## Лабораторная работа номер 4. Поиск колизии хеш-функции.
**Цель работы:** восстановить номер банковской карты по заданному хешу  (алгоритм хеширования - sha1) и информации о карте.

**Ход работы:**
1. Сначала я выяснил БИН коды карты при помощи доп информации о карте.
2. Далее произвел поиск и перебор номера карты зная БИН код и последние цифры карты. (здесь была задейственна также многопроцессорная обработка данных)
3. собрав статистику по поиску номеру карты я сделал нормальную диаграмму - график статистики поиска Коллизий.
4. сделал проверку номера банковской карты через алгоритм Луна.
5. сделал полноценное приложение с графическим дизайном. (использовал PyQT6) - основной файл main.py

**Вывод:** С поставленной задачей справился, номер банковской карты получил, сделал даже приложение используя PyQT6. Прикрепил в гитхабу демонстрационный кадр приложения в формате PNG.

2023-05-02 08:44 UTC, alxmcs requested changes
Общее замечание: - не наблюдаю никакого логирования в коде

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +        519998, 529025, 516451, 522327, 522329, 523760, 527652, 528528, 529158, 529460, 529856, 530176, 530429, 531452, \
Эти числа вынести в константы

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +            card_number = f'{card_bin}{card_number_:06d}{"0758"}'
Последние 4 цифры также параметризовать, как и хеш

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +from tqdm import tqdm
Сомневаюсь, что tqdm тут необходим. Он выводит прогресс где-то в консоли, при этом, очевидно, повисает основное окно программы. Такой себе ux.
Если хочется выводить прогресс бар - выводи его средствами pyqt.
![image](https://user-images.githubusercontent.com/70561974/235616537-232b8521-5663-4c0e-80fa-4da1ada5a940.png)

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +        for i in range(10):
Захардкоженный ренж. Было бы неплохо сделать его пропорциональным числу ядер.

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +            self.pools += 1
Из-за того, что ты сделал этот метод зависимым от значения классового атрибута (который никак не обнуляется), повторный запуск приведет к построению графика с 11 до 20.
![image](https://user-images.githubusercontent.com/70561974/235619160-b561becb-9df5-457a-9ee8-71ed276d0f25.png)

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +    def luna(self) -> bool:
Метод тоже не должен находиться в классе отрисовки гуи

2023-05-02 08:44 UTC, alxmcs commented on main.py
> +        return sum(card_numbers) % 10 == 0
Метод возвращает булевое значение, и все было бы прекрасно, только вот его нигде нельзя просмотреть. Оно улетает в никуда, потому что никакого окна не отрисовывается, никакое поле не обновляется и т.д.

2023-05-02 14:02 UTC, alxmcs requested changes
Ничего ты не ![image](https://user-images.githubusercontent.com/70561974/235689560-507233b2-84db-48da-8a5b-90fccd415250.png), ты все испортил.

2023-05-02 14:02 UTC, alxmcs commented on main.py
> +            logger.info("Номер карты не прошел проверку по алгоритму Луна")
Ты предлагаешь пользователю одним глазом смотреть в окно с гуями, а другим  - в консоль с (неработающим) логом? 
Ты хочешь быть Пол Потом от мира ux-дизайна?

2023-05-02 14:22 UTC, Santas7 commented
исправил код (весь..)

2023-05-02 14:33 UTC, alxmcs commented on card.py
> +from tqdm import tqdm
По-моему, в предыдущих ревью я ясно дал понять, что никакого tqdm быть не должно, если ты используешь pyqt.
Демонстрируй прогресс обработки пользователю средствами pyqt.

2023-05-02 15:25 UTC, Santas7 commented on card.py
> +    def check_card_number(card_number_) -> str:
а что здесь необходимо изменить? я просто не понимаю(

2023-05-02 15:54 UTC, Santas7 commented on card.py
> +from tqdm import tqdm
я почитал документацию по QProgressBar но так и не понимаю как мне сделать адекватно работающий прогресс бар( Можете подсказать?

2023-05-02 16:26 UTC, Santas7 commented on card.py
> +from tqdm import tqdm
судя по задаче у меня не получится сделать приемлемый прогресс бар, так как окно просто зависает и не дает пробегаться бару( в качестве решения нашел QThreadPool - но правда его тогда придется использовать вместо multiprocessing.pool

2023-05-03 11:54 UTC, alxmcs requested changes

2023-05-03 11:54 UTC, alxmcs commented on card.py
> +        global BINS, HASH, LATER_NUM
![image](https://user-images.githubusercontent.com/70561974/235906295-db74d09a-9e04-4fdc-ae4e-1153a5d122d3.png)

Вот это надо изменить.
Глобальные переменные тут не нужны.

2023-05-03 11:54 UTC, alxmcs commented on card.py
> +from tqdm import tqdm
Не вывозишь в прогресс бар - помести на хотя бы на форме текстовое окно, в которое будешь выводить статус того, чем софт занят.

Повторяю еще раз:
**никакого tqdm в коде быть не должно**
**сигнализация о прогрессе обработки в коде быть должна**

(Не я тебя заставлял рисовать графический интерфейс, ты сам это начал. Но раз ты это начал, реализуй это вменяемым образом)

2023-05-03 11:54 UTC, alxmcs commented on main.py
> +logger = logging.getLogger()
Еще раз - настрой логгер нормально.
У тебя есть десктопное приложение с графическим интерфейсом. Никому не упало смотреть в консоль. Логирование должно осуществляться в текстовый файл рядом с исполняемым скриптом.

2023-05-03 11:54 UTC, alxmcs commented on main.py
> +logger.setLevel('INFO')
Потрясающий логгер. Кроме его инициализации в этом скрипте с ним ничего не происходит.
Я бы порекомендовал поразмыслить на досуге, зачем производится логирование в приложениях и добавил бы его хоть где-нибудь. 

К примеру, для восстановления последовательности действий, которые привели к появлению внештатной операции, было бы полезно логировать то, какие контролы и в какое время были нажаты на форме.

2023-05-03 15:11 UTC, Santas7 commented on card.py
> +from tqdm import tqdm
Мне все же удалось после стратегических усилий сделать работаспособный прогресс бар)

<img width="467" alt="image" src="https://user-images.githubusercontent.com/86359412/235958919-48a42d3f-efea-44de-ab76-52df4598c2ec.png">

2023-05-03 15:15 UTC, Santas7 commented
Я убрал tqdm - заменив его на прогресс бар из PyQT (QProgressBar), сделал логирование наконец-то нормальное, и убрал глобальные переменные которые были не нужны в коде

2023-05-03 15:19 UTC, Santas7 commented
Еще я разобрался максимально с логированием, теперь при запуске создается файл .log в который сгружается последовательность действий при работе ( ошибки, предупреждения, сообщения об успешном прохождении какого-либо этапа... и др )

2023-05-04 08:45 UTC, alxmcs requested changes
Теперь меня устраивает практически все

2023-05-04 09:26 UTC, Santas7 commented
Я исправил код ( убрал комментарии вне докстрингов + изменил имя параметра card_number_ под PEP )

2023-05-04 09:36 UTC, alxmcs approved these changes
👍

2023-05-19 10:03 UTC, closed without merging