6211 Белякова В. И. Лаб 4 Вар 1
itsecd/isb-4 pull request #40
Opened 2023-06-05 16:34 UTC by Cat-sandwich

В  лабораторной работе было сделано:
-Поиск карты по ее хэшу с известным бином и последними 4 цифрами
-Хэш считался с помощью несколько процессоров(multiprocessing)
-Так же для взаимодействия с пользователем был использован logging
-Написана реализация алгоритма Луна, который позволяет узнать является ли номер карты корректным

2023-06-06 14:27 UTC, alxmcs requested changes

2023-06-06 15:13 UTC, alxmcs commented on README.md
> +*  -luhn LUHN_ALGORITHM, --luhn_algorithm MOON_ALGORITHM
>MOON_ALGORITHM

2023-06-06 16:43 UTC, Cat-sandwich commented on README.md
> +*  -luhn LUHN_ALGORITHM, --luhn_algorithm MOON_ALGORITHM
упс, пропустила(

2023-06-06 18:43 UTC, alxmcs approved these changes

2023-06-07 10:16 UTC, alxmcs commented
Зачтено

2023-06-07 10:16 UTC, closed without merging