Маясов Данила Вячеславович; 6211; Лаб 4, Вариант 11
itsecd/isb-4 pull request #44
Opened 2023-06-08 15:27 UTC by danyala1

В данной лабораторной работе я научился восстанавливать номер банковской карты по ее хешу и доп. информации: о типе карты, платежной системы.

2023-06-11 16:05 UTC, alxmcs requested changes

2023-06-11 16:05 UTC, alxmcs commented on card.py
> +    for i in range(100000,1000000):
Не учтены комбинации номеров, начинающиеся с нуля

2023-06-11 16:05 UTC, alxmcs commented on main.py
> +    if args.get_card_numb:
Вынести код под условием в отдельную функцию

2023-06-11 16:05 UTC, alxmcs commented on main.py
> +    elif args.luhn_algorithm:
Вынести код под условием в отдельную функцию

2023-06-11 16:05 UTC, alxmcs commented on main.py
> +    elif args.statistics:
Вынести код под условием в отдельную функцию

2023-06-11 16:05 UTC, alxmcs commented on data/card_number.txt
> +5534206055192305
Добавить сюда результаты проверки алгоритма Луна

2023-06-13 07:14 UTC, danyala1 commented
Все исправил

2023-06-13 08:07 UTC, alxmcs approved these changes

2023-06-13 08:11 UTC, alxmcs commented
Зачтено

2023-06-13 08:11 UTC, closed without merging