Гусарова Маргарита Олеговна 6211-100503D Основы информационной безопасности. 2 курс. Лабораторная №4
itsecd/isb-4 pull request #46
Opened 2023-06-10 06:43 UTC by MaargoGysarova

Восстановила номер банковской карты по ее хешу с использованием дополнительной информации о типе карты, выяснила корректность с помощью алгоритма Луна.

2023-06-11 15:52 UTC, alxmcs requested changes
Общее замечание - в репозитории нет результатов работы софта

2023-06-11 15:52 UTC, alxmcs commented on drowing.py
> +            for result in p.map(check_hash, range(99999, 10000000)):
Этот ренж не включает в себя комбинации цифр, начинающиеся с нуля, а конечное его число - в 10 раз больше необходимого

2023-06-11 15:52 UTC, alxmcs commented on hash.py
> +    if sum(all_number) % 10 == 0:
Переделать в тернарный оператор

2023-06-11 15:52 UTC, alxmcs commented on hash.py
> +        f'{SETTING["begin_digits"]}{number}{SETTING["last_digits"]}'.encode()).hexdigest() == f'{SETTING["hash"]}' \
Бесполезный f-стринг в правой части условия

2023-06-11 15:52 UTC, alxmcs commented on hash.py
> +        f'{SETTING["begin_digits"]}{number}{SETTING["last_digits"]}'.encode()).hexdigest() == f'{SETTING["hash"]}' \
Работа метода завязана на использование констант, соответственно, чтобы подобрать другой номер карты, нужно менять исходный код софта.

Здесь нужен некоторый файл с настройками приложения, который мог бы указать пользователь (в худшем случае, который бы лежал по захардкоженному пути, но был доступен для редактирования), посмотри примеры реализации в пул-риквестах своих однокурсников

2023-06-11 15:52 UTC, alxmcs commented on hash.py
> +    bin = [int(i) for i in SETTING['begin_digits']]
Аналогично

2023-06-11 15:52 UTC, alxmcs commented on hash.py
> +    end = [int(i) for i in SETTING['last_digits']]
Аналогично

2023-06-11 15:52 UTC, alxmcs commented on window.py
> +            f'Available card information: {SETTING["begin_digits"]}******{SETTING["last_digits"]}')
Аналогично

2023-06-11 15:52 UTC, alxmcs commented on settings.py
> +    SETTING= read_settings(path)
1) Этот метеод для перезаписи констант запускается только тут.
2) Перезаписывать константы - хреновая идея

Общие замечания касательно параметров приложения я описал выше

2023-06-12 07:02 UTC, alxmcs commented
Если необходимые изменения внесены, то ![image](https://github.com/itsecd/isb-4/assets/70561974/d9b7e12c-512d-4c2a-b6aa-d60e49a71e82)

2023-06-12 07:03 UTC, MaargoGysarova commented
> Если необходимые изменения внесены, то ![image](https://user-images.githubusercontent.com/70561974/245057373-d9b7e12c-512d-4c2a-b6aa-d60e49a71e82.png)

Точно, нажала

2023-06-12 07:27 UTC, alxmcs requested changes

2023-06-12 07:27 UTC, alxmcs commented on drowing.py
> +import multiprocessing as mp
>drowing.py

2023-06-12 07:27 UTC, alxmcs commented on settings.py
> +    SETTING = {
Либо вынести на уровень модуля, либо убрать капс

2023-06-12 07:27 UTC, alxmcs commented on hash.py
> +setting = read_settings('settings.json')
Убрать этот код, передавать настройки через параметры модулей

2023-06-12 07:27 UTC, alxmcs commented on hash.py
> +    return True if sum(all_number) % 10 == 0 else False
Синтаксис условия можно упростить

2023-06-12 07:54 UTC, MaargoGysarova commented on drowing.py
> +import multiprocessing as mp
А что здесь ?

2023-06-12 08:13 UTC, alxmcs commented on drowing.py
> +import multiprocessing as mp
![image](https://github.com/itsecd/isb-4/assets/70561974/ed99ae01-a604-45a7-8a6f-1a9ea70df253)

2023-06-12 08:13 UTC, MaargoGysarova commented on drowing.py
> +import multiprocessing as mp
ааа 😂😂😂

2023-06-12 09:09 UTC, alxmcs approved these changes

2023-06-13 08:11 UTC, alxmcs commented
Зачтено

2023-06-13 08:11 UTC, closed without merging