6213 Елагин Денис Евгеньевич Лаб.4 Вар.3
itsecd/isb-4 pull request #5
Opened 2023-04-29 16:38 UTC by Donistr

Написанный код позволяет:
-подобрать номер карты по заданному хэшу
-проверить корректность полученного номера карты, с помощью алгоритма Луна
-визуализировать статистику зависимости кол-ва потоков от времени при подборе номера карты

Используя алгоритм хэширования sha1 был получен номер карты, который по результатам проверки алгоритмом Луна оказался некорректным

2023-05-02 08:57 UTC, alxmcs requested changes

2023-05-02 08:57 UTC, alxmcs commented on vizualization.py
> +    plt.bar(x, y, color='gold', width=0.05)
https://github.com/Santas7/isb-4/blob/main/graph.png
Узнали? Согласны?

Хотя бы ширину колонок и цвет меняли, если друг у друга код крадете.

2023-05-02 08:57 UTC, alxmcs commented on file_manager.py
> +    def write_statistic_to_the_end(self, cores: int, time: float) -> None:
Было бы неплохо использовать какой-то чуть более продвинутый формат, чем просто текстовый файл, например что-то вроде:
```py
import csv

with open('path/to/csv_file', 'w') as f:
    writer = csv.writer(f)
   # и так далее
```

2023-05-02 08:57 UTC, alxmcs commented on file_manager.py
> +    def read_statistic(self) -> dict:
Соответственно, этот метод тоже надо бы изменить

2023-05-02 17:14 UTC, Donistr commented on vizualization.py
> +    plt.bar(x, y, color='gold', width=0.05)
![Screenshot_1163](https://user-images.githubusercontent.com/114046902/235737188-a88c5b42-7e4f-4cf4-bf95-4f26b1ee0549.png)
код из вашего ноутбука

2023-05-03 07:26 UTC, alxmcs approved these changes

2023-05-19 10:04 UTC, closed without merging